### ISSUE TITLE
Display dropdown menu in scrapbook does not always work

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#15]
In the scrapbook, I went to the display menu and clicked "grandpa's Recordings" under "Tagged adults." I was expecting my scrapbook to update and only display the one recording that grandpa was tagged in. Instead, nothing happened (all recordings remained visible). I refreshed and tried again, same problem. I was able to sort by other tagged users, just not this particular user.

Also, I (account owner) do not appear in the "Tagged adults" section of the "display" dropdown menu. Therefore, I am not able to search for recordings that I am in. 

iPhone 7 / Safari / iOS 13.6
laptop / Windows 10 / Chrome 83

**Comment by ichimura-a** [comment]
Also happened to me.
MacBook Air / Chrome Version 84.0.4147.105 / macOS Catalina Version 10.15.6

- After (un)checking "Only Clips With No Label", nothing changed.
- The search bar was not functioning
- none of the "Tagged Adults" are filtered as well

**Comment by lorenachipstudio** [comment]
Thanks for reporting this- we'll take a look! 

Lorena

**Comment by lorenachipstudio** [comment]
@koppen152 @ichimura-a We've deployed a fix onto the staging site for this. Can you confirm that the bug has been fixed?

**Comment by koppen152** [comment]
@lorenachipstudio the drop down menu worked as expected, but I (the account owner) do not appear in the drop down menu.

**Comment by ichimura-a** [comment]
@lorenachipstudio The drop down menu works great, although the "Only Clips With No Label" checkbox still does not.

**Comment by lorenachipstudio** [comment]
@ichimura-a We'll take a look- thank you for the check!

**Comment by lorenachipstudio** [comment]
@ichimura-a We updated the "Only Clips with No Label" fix and deployed it to staging. Can you confirm it's fixed?

**Comment by ichimura-a** [comment]
@lorenachipstudio Yes, the "Only Clips with No Label" works for me now. Thanks!
