### ISSUE TITLE
Can't get rid of question marks

### ISSUE THREAD

**Issue by ythuang123** [jkhartshorne/KidTalkIssues#21]
The old tiles show up with question marks. When I click to edit them, I can add a label, which shows up under the question mark. I thought the question marks were placeholders to get folks to add text but maybe I'm wrong? How are we supposed to get rid of the questions marks? 

![image](https://user-images.githubusercontent.com/68764650/89306757-4c060200-d63e-11ea-8dc2-7458892bae08.png)

Chrome, Window 10 Enterprise v. 1909 (OS build 18563.959), ThinkPad X1 Carbon 4G

**Comment by lorenachipstudio** [comment]
@ythuang123 We'll take a look- thank you!

**Comment by lorenachipstudio** [comment]
@ythuang123 The question marks are actually placeholders for icons rather than text. If no selected icons exist for the clip, it will show the question mark instead. We are working on a way to go back in to edit selected icons for clips which is currently in development.

**Comment by lorenachipstudio** [comment]
@ythuang123 this should be resolved in staging- can you confirm?

**Comment by ythuang123** [comment]
Hi Lorena -- Sorry for the delay. I'm back on the staging site, but I still can't edit the selected icons for clips. The only options I see are edit label, submit, and delete clip (same as last time --see below). Can you confirm that something has changed? 

![image](https://user-images.githubusercontent.com/68764650/89786857-98dc5380-daea-11ea-9845-6a2b0946c7ce.png)

**Comment by jkhartshorne** [comment]
I think this is still open. See: https://github.com/alexchippendale/KidTalkRemainingTasks/issues/4

**Comment by alexchippendale** [comment]
@jkhartshorne @ythuang123 Yes this is in development right now, apologies for the confusion I believe I referenced this issue by mistake when speaking to @lorenachipstudio about a separate issue.

@jkhartshorne Would you mind closing this one here (or in the Remaining Tasks repo) so that we don't have a duplicate?
