### ISSUE TITLE
Downloadable app is down

### ISSUE THREAD

**Issue by koppen152** [jkhartshorne/KidTalkIssues#68]
When I open the downloadable app on my iPhone 8 (iOS 14.3), I’m having the same problem that was recently fixed in staging and production for the browser-based app. When I open the app, I get the “report an error” page, and clicking the menu icon brings me very large images that I can’t click.

![83BEBB3E-F598-49B2-81C4-DB06C94C2C6D](https://user-images.githubusercontent.com/54418192/106172865-49a1e200-6161-11eb-8bbb-03e9dbf6970b.jpeg)
![1C9AF261-5529-4A50-BED2-5C846407EFB2](https://user-images.githubusercontent.com/54418192/106172868-49a1e200-6161-11eb-9a6a-f0a04e4640da.png)

**Comment by alexchippendale** [comment]
@koppen152 Can you check this again? This should be fixed now, can you confirm? Thanks!

**Comment by koppen152** [comment]
Now I get a blank page when I open the downloadable app. I tried deleting and reinstalling, and I still get a blank page with no icons or images.

**Comment by alexchippendale** [comment]
@koppen152 Hmmm, taking a look.

**Comment by alexchippendale** [comment]
We deployed a fix for this, the downloadable beta app should be back up now, you may have to exit the app first.

**Comment by koppen152** [comment]
Works now! I'll open some new issues for the bugs I found.

**Comment by alexchippendale** [comment]
Okay great, thanks!
